
export enum ExerciseType {
  HOME = 'HOME',
  BREATHING = 'BREATHING',
  SENSES = 'SENSES',
  GRATITUDE = 'GRATITUDE',
  MEDITATION = 'MEDITATION',
  VISUALIZATION = 'VISUALIZATION',
  BODY_SCAN = 'BODY_SCAN',
  MINDFUL_EATING = 'MINDFUL_EATING',
  WALKING_MEDITATION = 'WALKING_MEDITATION',
  MINDFUL_MOVEMENT = 'MINDFUL_MOVEMENT',
  SOUND_MEDITATION = 'SOUND_MEDITATION',
  MINDFUL_PHOTOS = 'MINDFUL_PHOTOS',
  WELLNESS = 'WELLNESS',
  HISTORY = 'HISTORY'
}

export interface ExerciseStep {
  text: string;
  duration?: number;
}
